BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial FastLed stringQueue lsem SimpleTimer

USER_LIB_PATH = $(realpath ../SCS/arduino)

AVRDUDE_ARD_BAUDRATE = 57600

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk


